name: "Build and publish images"

on:
  push:
    tags:
      - '*.*.*'
      - "!workflow-poc-*"
    branches:
      - develop
  
jobs:
  build_push:
    strategy:
      matrix:
        services:
          - "package1"
          - "package2"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.services }}
          file: ${{ matrix.services }}/Dockerfile
          push: false
          tags: |
            ${{ matrix.services }}:${{ github.sha }}
            ${{ matrix.services }}:${{ github.ref_name }}
  